### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by joshcough** [mitar/nxt#1]
Do you have any examples of how to run this? I just got a new NTX and I would love to try it, but I have no idea where to start.

**Comment by joshcough** [comment]
Sorry, never mind. I got the EV3.

**Comment by mitar** [comment]
See tests for an example.

Also, feel free to send a pull request with updates for EV3.

**Comment by joshcough** [comment]
The tests lack a bit of _howness_ about them, for lack of a better word. Could you maybe put just a couple of lines in the readme? If so, then yeah, I can try to work on EV3.

**Comment by mitar** [comment]
More examples are also in the `src` directory.

**Comment by joshcough** [comment]
I guess the main question is just _how_ are these ran? Do I plug my computer into my mindstorms and then run an executable and/or fire up ghci and call code? Could you clarify that a little?

**Comment by mitar** [comment]
You make a Haskell program, you compile it and you run it. So it is remote control. You do not compile Haskell for NXT.

It can work over USB or Bluetooth.
