### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by madjestic** [mitar/nxt#2]
cabal install
Resolving dependencies...
Configuring NXT-0.2.3...
Building NXT-0.2.3...
Failed to install NXT-0.2.3
Build log ( /home/madjestic/.cabal/logs/NXT-0.2.3.log ):
Configuring NXT-0.2.3...
Building NXT-0.2.3...
Preprocessing library NXT-0.2.3...
[ 1 of 12] Compiling Robotics.NXT.Externals ( lib/Robotics/NXT/Externals.hs, dist/build/Robotics/NXT/Externals.dyn_o )
[ 2 of 12] Compiling Robotics.NXT.Internals ( lib/Robotics/NXT/Internals.hs, dist/build/Robotics/NXT/Internals.dyn_o )

lib/Robotics/NXT/Internals.hs:15:58:
    No instance for (Applicative NXT)
      arising from the 'deriving' clause of a data type declaration
    Possible fix:
      use a standalone 'deriving instance' declaration,
        so you can specify the instance context yourself
    When deriving the instance for (Monad NXT)
cabal: Error: some packages failed to install:
NXT-0.2.3 failed during the building phase. The exception was:
ExitFailure 1

**Comment by mitar** [comment]
Which version of GHC?

**Comment by madjestic** [comment]
7.10.3

**Comment by mitar** [comment]
Sorry, at the time I do not have time to look into this. If you manage to fix it, please do a pull request.

**Comment by mitar** [comment]
Fixed with #3.
